// value of AUTHORIZATION_URL has been copied from HubSpot app creation page in developer account
const AUTHORIZATION_URL = `https://app.hubspot.com/oauth/authorize?client_id=49985d26-b5f2-4d4f-8f8f-41d2416de4ac&redirect_uri=http://localhost:3000/authenticated&scope=contacts%20content%20oauth`;

// values of client_id, client_secret and redirect_uri have been copied from HubSpot app creation page in developer account
const auth = {
  grant_type: "authorization_code",
  client_id: "49985d26-b5f2-4d4f-8f8f-41d2416de4ac",
  client_secret: "14d2d8b1-c225-4d40-bffc-bdbf86b8df9f",
  redirect_uri: "http://localhost:3000/authenticated",
  code: "",
};

//This is a demo page data. This object has been obtained by doing a GET request to the HubSpot API endpoint https://api.hubapi.com/cms/v3/pages/site-pages

const page = {
  archived: false,
  attachedStylesheets: [],
  authorName: "Roman Kozak",
  categoryId: 1,
  contentTypeCategory: 4,
  createdAt: "2021-10-26T17:11:05.924Z",
  createdById: "8835724",
  currentState: "PUBLISHED",
  deletedAt: "1970-01-01T00:00:00Z",
  domain: "",
  featuredImage: "",
  featuredImageAltText: "",
  htmlTitle: "Home demo page",
  id: "58408849699",
  layoutSections: {
    dnd_area: {
      cells: [],
      cssClass: "",
      cssId: "",
      cssStyle: "",
      label: "Main section",
      name: "dnd_area",
      params: {},
      rowMetaData: [
        {
          cssClass: "dnd-section",
          styles: {
            backgroundColor: { a: 1, b: 252, g: 250, r: 248 },
            forceFullWidthSection: false,
          },
        },
        { cssClass: "dnd-section", styles: { forceFullWidthSection: false } },
        {
          cssClass: "dnd-section",
          styles: {
            backgroundColor: { a: 1, b: 252, g: 250, r: 248 },
            forceFullWidthSection: false,
          },
        },
        {
          cssClass: "dnd-section",
          styles: {
            backgroundImage: {
              backgroundPosition: "MIDDLE_CENTER",
              backgroundSize: "cover",
              imageUrl:
                "//f.hubspotusercontent20.net/hubfs/20508627/raw_assets/public/demo_theme/images/large-placeholder-image.png",
            },
            forceFullWidthSection: false,
            maxWidthSectionCentering: 700,
          },
        },
        {
          cssClass: "dnd-section",
          styles: {
            backgroundColor: { a: 1, b: 252, g: 250, r: 248 },
            forceFullWidthSection: false,
          },
        },
      ],
      rows: [
        {
          0: {
            cells: [],
            cssClass: "",
            cssId: "",
            cssStyle: "",
            name: "dnd_area-dnd_partial-1-module-1",
            params: {
              css_class: "dnd-module",
              extra_classes: "widget-type-linked_image",
              img: {
                alt: "behance-team-thumbnail",
                height: 276,
                loading: "disabled",
                max_height: 276,
                max_width: 276,
                size_type: "auto_custom_max",
                src: "https://f.hubspotusercontent20.net/hubfs/20508627/behance-team-thumbnail.jpg",
                width: 276,
              },
              module_id: 1155231,
              path: "@hubspot/linked_image",
              schema_version: 2,
              smart_objects: [],
              smart_type: "NOT_SMART",
              styles: {},
              wrap_field_tag: "div",
            },
            rowMetaData: [],
            rows: [],
            styles: { verticalAlignment: "MIDDLE" },
            type: "custom_widget",
            w: 6,
            x: 0,
          },
          6: {
            cells: [],
            cssClass: "",
            cssId: "",
            cssStyle: "",
            name: "dnd_area-dnd_partial-1-column-2",
            params: { css_class: "dnd-column" },
            rowMetaData: [{ cssClass: "dnd-row" }, { cssClass: "dnd-row" }],
            rows: [
              {
                0: {
                  cells: [],
                  cssClass: "",
                  cssId: "",
                  cssStyle: "",
                  name: "dnd_area-dnd_partial-1-module-3",
                  params: {
                    css_class: "dnd-module",
                    extra_classes: "widget-type-rich_text",
                    html: "<h1>Demo home page title</h1>\n<p>Use this space to tell everyone about what you have to offer.</p>",
                    module_id: 1155639,
                    path: "@hubspot/rich_text",
                    schema_version: 2,
                    smart_objects: [],
                    smart_type: "NOT_SMART",
                    styles: {},
                    wrap_field_tag: "div",
                  },
                  rowMetaData: [],
                  rows: [],
                  type: "custom_widget",
                  w: 12,
                  x: 0,
                },
              },
              {
                0: {
                  cells: [],
                  cssClass: "",
                  cssId: "",
                  cssStyle: "",
                  name: "dnd_area-dnd_partial-1-module-4",
                  params: {
                    css_class: "dnd-module",
                    extra_classes: "widget-type-form",
                    module_id: 1155238,
                    path: "@hubspot/form",
                    schema_version: 2,
                    smart_objects: [],
                    smart_type: "NOT_SMART",
                    styles: {},
                    wrap_field_tag: "div",
                  },
                  rowMetaData: [],
                  rows: [],
                  type: "custom_widget",
                  w: 12,
                  x: 0,
                },
              },
            ],
            styles: { verticalAlignment: "MIDDLE" },
            type: "cell",
            w: 6,
            x: 6,
          },
        },
        {
          0: {
            cells: [],
            cssClass: "",
            cssId: "",
            cssStyle: "",
            name: "dnd_area-dnd_partial-2-module-1",
            params: {
              css_class: "dnd-module",
              extra_classes: "widget-type-rich_text",
              html: "<h2>Provide more details here.</h2>\n<p>Use text and images to tell your company’s story. Explain what makes your product or service extraordinary.</p>",
              module_id: 1155639,
              path: "@hubspot/rich_text",
              schema_version: 2,
              smart_objects: [],
              smart_type: "NOT_SMART",
              styles: {},
              wrap_field_tag: "div",
            },
            rowMetaData: [],
            rows: [],
            styles: { verticalAlignment: "MIDDLE" },
            type: "custom_widget",
            w: 6,
            x: 0,
          },
          6: {
            cells: [],
            cssClass: "",
            cssId: "",
            cssStyle: "",
            name: "dnd_area-dnd_partial-2-module-2",
            params: {
              css_class: "dnd-module",
              extra_classes: "widget-type-linked_image",
              img: {
                alt: "Stock placeholder image with grayscale geometrical mountain landscape",
                loading: "disabled",
                max_height: 451,
                max_width: 605,
                size_type: "auto_custom_max",
                src: "//f.hubspotusercontent20.net/hubfs/20508627/raw_assets/public/demo_theme/images/grayscale-mountain.png",
              },
              module_id: 1155231,
              path: "@hubspot/linked_image",
              schema_version: 2,
              smart_objects: [],
              smart_type: "NOT_SMART",
              styles: {},
              wrap_field_tag: "div",
            },
            rowMetaData: [],
            rows: [],
            styles: { verticalAlignment: "MIDDLE" },
            type: "custom_widget",
            w: 6,
            x: 6,
          },
        },
        {
          0: {
            cells: [],
            cssClass: "",
            cssId: "",
            cssStyle: "",
            name: "dnd_area-module-3",
            params: {
              css_class: "dnd-module",
              extra_classes: "widget-type-linked_image",
              img: {
                alt: "Stock placeholder image with grayscale geometrical mountain landscape",
                loading: "lazy",
                max_height: 451,
                max_width: 605,
                size_type: "auto_custom_max",
                src: "//f.hubspotusercontent20.net/hubfs/20508627/raw_assets/public/demo_theme/images/grayscale-mountain.png",
              },
              path: "@hubspot/linked_image",
              schema_version: 2,
              smart_objects: [],
              smart_type: "NOT_SMART",
              styles: {},
              wrap_field_tag: "div",
            },
            rowMetaData: [],
            rows: [],
            styles: { verticalAlignment: "MIDDLE" },
            type: "custom_widget",
            w: 6,
            x: 0,
          },
          6: {
            cells: [],
            cssClass: "",
            cssId: "",
            cssStyle: "",
            name: "dnd_area-module-4",
            params: {
              css_class: "dnd-module",
              extra_classes: "widget-type-rich_text",
              html: "<h2>Provide more details here.</h2><p>Use text and images to tell your company’s story. Explain what makes your product or service extraordinary.</p>",
              path: "@hubspot/rich_text",
              schema_version: 2,
              smart_objects: [],
              smart_type: "NOT_SMART",
              styles: {},
              wrap_field_tag: "div",
            },
            rowMetaData: [],
            rows: [],
            styles: { verticalAlignment: "MIDDLE" },
            type: "custom_widget",
            w: 6,
            x: 6,
          },
        },
        {
          0: {
            cells: [],
            cssClass: "",
            cssId: "",
            cssStyle: "",
            name: "dnd_area-dnd_partial-5-column-1",
            params: { css_class: "dnd-column" },
            rowMetaData: [
              { cssClass: "dnd-row", styles: {} },
              { cssClass: "dnd-row" },
            ],
            rows: [
              {
                0: {
                  cells: [],
                  cssClass: "",
                  cssId: "",
                  cssStyle: "",
                  name: "dnd_area-dnd_partial-5-module-2",
                  params: {
                    css_class: "dnd-module",
                    extra_classes: "widget-type-rich_text",
                    html: '<div style="text-align: center"><h2>Provide an excerpt here</h2><p>Use text and images to tell your company’s story. Explain what makes your product or service extraordinary.</p></div>',
                    module_id: 1155639,
                    path: "@hubspot/rich_text",
                    schema_version: 2,
                    smart_objects: [],
                    smart_type: "NOT_SMART",
                    styles: {},
                    wrap_field_tag: "div",
                  },
                  rowMetaData: [],
                  rows: [],
                  type: "custom_widget",
                  w: 12,
                  x: 0,
                },
              },
              {
                0: {
                  cells: [],
                  cssClass: "",
                  cssId: "",
                  cssStyle: "",
                  name: "dnd_area-dnd_partial-5-module-3",
                  params: {
                    button_text: "Get started",
                    css_class: "dnd-module",
                    module_id: 58406480045,
                    path: "../modules/button",
                    schema_version: 2,
                    smart_objects: [],
                    smart_type: "NOT_SMART",
                    styles: {
                      alignment: {
                        alignment: { css: "", horizontal_align: "CENTER" },
                      },
                    },
                    wrap_field_tag: "div",
                  },
                  rowMetaData: [],
                  rows: [],
                  type: "custom_widget",
                  w: 12,
                  x: 0,
                },
              },
            ],
            styles: { verticalAlignment: "MIDDLE" },
            type: "cell",
            w: 12,
            x: 0,
          },
        },
        {
          0: {
            cells: [],
            cssClass: "",
            cssId: "",
            cssStyle: "",
            name: "dnd_area-dnd_partial-6-column-1",
            params: { css_class: "dnd-column" },
            rowMetaData: [{ cssClass: "dnd-row" }, { cssClass: "dnd-row" }],
            rows: [
              {
                0: {
                  cells: [],
                  cssClass: "",
                  cssId: "",
                  cssStyle: "",
                  name: "dnd_area-dnd_partial-6-module-2",
                  params: {
                    css_class: "dnd-module",
                    extra_classes: "widget-type-linked_image",
                    img: {
                      alt: "Stock placeholder image with grayscale geometrical mountain landscape",
                      loading: "lazy",
                      max_height: 451,
                      max_width: 605,
                      size_type: "auto_custom_max",
                      src: "//f.hubspotusercontent20.net/hubfs/20508627/raw_assets/public/demo_theme/images/grayscale-mountain.png",
                    },
                    module_id: 1155231,
                    path: "@hubspot/linked_image",
                    schema_version: 2,
                    smart_objects: [],
                    smart_type: "NOT_SMART",
                    styles: {},
                    wrap_field_tag: "div",
                  },
                  rowMetaData: [],
                  rows: [],
                  type: "custom_widget",
                  w: 12,
                  x: 0,
                },
              },
              {
                0: {
                  cells: [],
                  cssClass: "",
                  cssId: "",
                  cssStyle: "",
                  name: "dnd_area-dnd_partial-6-module-3",
                  params: {
                    css_class: "dnd-module",
                    extra_classes: "widget-type-rich_text",
                    html: "<h3>Feature one</h3><p>Use text and images to tell your company’s story. Explain what makes your product or service extraordinary.</p>",
                    module_id: 1155639,
                    path: "@hubspot/rich_text",
                    schema_version: 2,
                    smart_objects: [],
                    smart_type: "NOT_SMART",
                    styles: {},
                    wrap_field_tag: "div",
                  },
                  rowMetaData: [],
                  rows: [],
                  type: "custom_widget",
                  w: 12,
                  x: 0,
                },
              },
            ],
            styles: { verticalAlignment: "MIDDLE" },
            type: "cell",
            w: 4,
            x: 0,
          },
          4: {
            cells: [],
            cssClass: "",
            cssId: "",
            cssStyle: "",
            name: "dnd_area-dnd_partial-6-column-4",
            params: { css_class: "dnd-column" },
            rowMetaData: [{ cssClass: "dnd-row" }, { cssClass: "dnd-row" }],
            rows: [
              {
                0: {
                  cells: [],
                  cssClass: "",
                  cssId: "",
                  cssStyle: "",
                  name: "dnd_area-dnd_partial-6-module-5",
                  params: {
                    css_class: "dnd-module",
                    extra_classes: "widget-type-linked_image",
                    img: {
                      alt: "Stock placeholder image with grayscale geometrical mountain landscape",
                      loading: "lazy",
                      max_height: 451,
                      max_width: 605,
                      size_type: "auto_custom_max",
                      src: "//f.hubspotusercontent20.net/hubfs/20508627/raw_assets/public/demo_theme/images/grayscale-mountain.png",
                    },
                    module_id: 1155231,
                    path: "@hubspot/linked_image",
                    schema_version: 2,
                    smart_objects: [],
                    smart_type: "NOT_SMART",
                    styles: {},
                    wrap_field_tag: "div",
                  },
                  rowMetaData: [],
                  rows: [],
                  type: "custom_widget",
                  w: 12,
                  x: 0,
                },
              },
              {
                0: {
                  cells: [],
                  cssClass: "",
                  cssId: "",
                  cssStyle: "",
                  name: "dnd_area-dnd_partial-6-module-6",
                  params: {
                    css_class: "dnd-module",
                    extra_classes: "widget-type-rich_text",
                    html: "<h3>Feature two</h3><p>Use text and images to tell your company’s story. Explain what makes your product or service extraordinary.</p>",
                    module_id: 1155639,
                    path: "@hubspot/rich_text",
                    schema_version: 2,
                    smart_objects: [],
                    smart_type: "NOT_SMART",
                    styles: {},
                    wrap_field_tag: "div",
                  },
                  rowMetaData: [],
                  rows: [],
                  type: "custom_widget",
                  w: 12,
                  x: 0,
                },
              },
            ],
            styles: { verticalAlignment: "MIDDLE" },
            type: "cell",
            w: 4,
            x: 4,
          },
          8: {
            cells: [],
            cssClass: "",
            cssId: "",
            cssStyle: "",
            name: "dnd_area-dnd_partial-6-column-7",
            params: { css_class: "dnd-column" },
            rowMetaData: [{ cssClass: "dnd-row" }, { cssClass: "dnd-row" }],
            rows: [
              {
                0: {
                  cells: [],
                  cssClass: "",
                  cssId: "",
                  cssStyle: "",
                  name: "dnd_area-dnd_partial-6-module-8",
                  params: {
                    css_class: "dnd-module",
                    extra_classes: "widget-type-linked_image",
                    img: {
                      alt: "Stock placeholder image with grayscale geometrical mountain landscape",
                      loading: "lazy",
                      max_height: 451,
                      max_width: 605,
                      size_type: "auto_custom_max",
                      src: "//f.hubspotusercontent20.net/hubfs/20508627/raw_assets/public/demo_theme/images/grayscale-mountain.png",
                    },
                    module_id: 1155231,
                    path: "@hubspot/linked_image",
                    schema_version: 2,
                    smart_objects: [],
                    smart_type: "NOT_SMART",
                    styles: {},
                    wrap_field_tag: "div",
                  },
                  rowMetaData: [],
                  rows: [],
                  type: "custom_widget",
                  w: 12,
                  x: 0,
                },
              },
              {
                0: {
                  cells: [],
                  cssClass: "",
                  cssId: "",
                  cssStyle: "",
                  name: "dnd_area-dnd_partial-6-module-9",
                  params: {
                    css_class: "dnd-module",
                    extra_classes: "widget-type-rich_text",
                    html: "<h3>Feature three</h3><p>Use text and images to tell your company’s story. Explain what makes your product or service extraordinary.</p>",
                    module_id: 1155639,
                    path: "@hubspot/rich_text",
                    schema_version: 2,
                    smart_objects: [],
                    smart_type: "NOT_SMART",
                    styles: {},
                    wrap_field_tag: "div",
                  },
                  rowMetaData: [],
                  rows: [],
                  type: "custom_widget",
                  w: 12,
                  x: 0,
                },
              },
            ],
            styles: { verticalAlignment: "MIDDLE" },
            type: "cell",
            w: 4,
            x: 8,
          },
        },
      ],
      type: "cell",
      w: 12,
      x: 0,
    },
  },
  name: "Home demo page",
  pageRedirected: false,
  publicAccessRules: [],
  publicAccessRulesEnabled: false,
  publishDate: "1970-01-01T00:00:00Z",
  publishImmediately: true,
  published: true,
  slug: "demo-homepage",
  state: "PUBLISHED_OR_SCHEDULED",
  subcategory: "site_page",
  templatePath: "demo_theme/templates/home.html",
  updatedAt: "2021-10-31T19:06:21.742Z",
  updatedById: "8835724",
  url: "http://20508627.hs-sites.com/demo-homepage",
  useFeaturedImage: false,
  widgetContainers: {},
  widgets: {},
};

module.exports = {
  page: page,
  auth: auth,
};
